### ISSUE TITLE
there is not a file called "robotmodels/wam7_model.pkl"

### ISSUE THREAD

**Issue by NKU-ZiXuan** [cdsousa/IROS2013-Feas-Ident-WAM7#2]
there is not a file called "robotmodels/wam7_model.pkl", could you please upload it?

**Comment by cdsousa** [comment]
That file is supposed to be generated at the beginning of the [notebook](https://github.com/cdsousa/IROS2013-Feas-Ident-WAM7/blob/master/Paper%20IROS2013%20-%20Phys%20Feas%20Dyn%20Param%20Ident%207-DOF%20WAM%20Rob.ipynb), in the section "1 - Robot Model"/"Model Generation"
